name: Github actions and continuous integration
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install all dependencies
        run: npm ci

      - name: static code
        run: npm run lint

      - name: E2E on Chrome
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headless: true
